### ISSUE TITLE
error with sbt run

### ISSUE THREAD

**Issue by eahmedsalman** [ucb-bar/chisel-tutorial#133]
at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
        at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
        at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
        at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1429)
        at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1403)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
        at sbt.std.Transform$$anon$4.work(System.scala:66)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:271)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
[info] Attempting to fetch org.scala-sbt:compiler-bridge_2.11:1.1.1.
[error] ## Exception when compiling 56 sources to C:\Users\salman\chisel-tutorial\target\scala-2.11\classes
[error] null
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[error] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[error] java.base/java.lang.reflect.Method.invoke(Unknown Source)
[error] sbt.internal.inc.RawCompiler.getReporter$1(RawCompiler.scala:50)
[error] sbt.internal.inc.RawCompiler.apply(RawCompiler.scala:71)
[error] sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$6(AnalyzingCompiler.scala:350)
[error] sbt.internal.inc.AnalyzingCompiler$.handleCompilationError$1(AnalyzingCompiler.scala:327)
[error] sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4(AnalyzingCompiler.scala:346)
[error] sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4$adapted(AnalyzingCompiler.scala:341)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error] sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2(AnalyzingCompiler.scala:341)
[error] sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2$adapted(AnalyzingCompiler.scala:335)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error] sbt.internal.inc.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:335)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:271)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3$adapted(ZincComponentCompiler.scala:256)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$2(ZincComponentCompiler.scala:256)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.util.BufferedLogger.bufferQuietly(BufferedLogger.scala:106)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1(ZincComponentCompiler.scala:256)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1$adapted(ZincComponentCompiler.scala:253)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error] sbt.internal.inc.ZincComponentCompiler.compileAndInstall(ZincComponentCompiler.scala:253)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compiledBridgeJar$1(ZincComponentCompiler.scala:219)
[error] sbt.internal.inc.IfMissing$Define.run(IfMissing.scala:19)
[error] sbt.internal.inc.ZincComponentManager.createAndCache$1(ZincComponentManager.scala:46)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$3(ZincComponentManager.scala:57)
[error] sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:38)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$2(ZincComponentManager.scala:57)
[error] sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:87)
[error] xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] xsbt.boot.Using$.withResource(Using.scala:10)
[error] xsbt.boot.Using$.apply(Using.scala:9)
[error] xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] xsbt.boot.Locks$.apply(Locks.scala:28)
[error] sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:87)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$lockSecondaryCache$1(ZincComponentManager.scala:84)
[error] scala.Option.map(Option.scala:146)
[error] sbt.internal.inc.ZincComponentManager.lockSecondaryCache(ZincComponentManager.scala:82)
[error] sbt.internal.inc.ZincComponentManager.fromSecondary$1(ZincComponentManager.scala:55)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$6(ZincComponentManager.scala:61)
[error] sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:38)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$5(ZincComponentManager.scala:61)
[error] sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:87)
[error] xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] xsbt.boot.Using$.withResource(Using.scala:10)
[error] xsbt.boot.Using$.apply(Using.scala:9)
[error] xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] xsbt.boot.Locks$.apply(Locks.scala:28)
[error] sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:87)
[error] sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:78)
[error] sbt.internal.inc.ZincComponentManager.files(ZincComponentManager.scala:61)
[error] sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:66)
[error] sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:219)
[error] sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:84)
[error] sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:91)
[error] sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:249)
[error] sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:267)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:234)
[error] sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:134)
[error] sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:121)
[error] sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:78)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:88)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1429)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1403)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] sbt.std.Transform$$anon$4.work(System.scala:66)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:271)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error] java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error] java.base/java.lang.Thread.run(Unknown Source)
[error]
[error] java.lang.NullPointerException
[error]         at scala.reflect.io.JavaToolsPlatformArchive.iterator(ZipArchive.scala:301)
[error]         at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]         at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:92)
[error]         at scala.tools.nsc.util.DirectoryClassPath.traverse(ClassPath.scala:277)
[error]         at scala.tools.nsc.util.DirectoryClassPath.x$15$lzycompute(ClassPath.scala:299)
[error]         at scala.tools.nsc.util.DirectoryClassPath.x$15(ClassPath.scala:299)
[error]         at scala.tools.nsc.util.DirectoryClassPath.packages$lzycompute(ClassPath.scala:299)
[error]         at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:299)
[error]         at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:264)
[error]         at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:358)
[error]         at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:358)
[error]         at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[error]         at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.tools.nsc.util.MergedClassPath.packages$lzycompute(ClassPath.scala:358)
[error]         at scala.tools.nsc.util.MergedClassPath.packages(ClassPath.scala:353)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$1.apply$mcV$sp(SymbolLoaders.scala:269)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$1.apply(SymbolLoaders.scala:260)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$1.apply(SymbolLoaders.scala:260)
[error]         at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:260)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:211)
[error]         at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
[error]         at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:256)
[error]         at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:73)
[error]         at scala.tools.nsc.Global.rootMirror(Global.scala:71)
[error]         at scala.tools.nsc.Global.rootMirror(Global.scala:39)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1390)
[error]         at scala.tools.nsc.Global$Run.<init>(Global.scala:1242)
[error]         at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[error]         at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[error]         at scala.tools.nsc.Driver.process(Driver.scala:51)
[error]         at scala.tools.nsc.Main.process(Main.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[error]         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[error]         at sbt.internal.inc.RawCompiler.getReporter$1(RawCompiler.scala:50)
[error]         at sbt.internal.inc.RawCompiler.apply(RawCompiler.scala:71)
[error]         at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$6(AnalyzingCompiler.scala:350)
[error]         at sbt.internal.inc.AnalyzingCompiler$.handleCompilationError$1(AnalyzingCompiler.scala:327)
[error]         at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4(AnalyzingCompiler.scala:346)
[error]         at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$4$adapted(AnalyzingCompiler.scala:341)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error]         at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2(AnalyzingCompiler.scala:341)
[error]         at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$2$adapted(AnalyzingCompiler.scala:335)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error]         at sbt.internal.inc.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:335)
[error]         at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:271)
[error]         at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3$adapted(ZincComponentCompiler.scala:256)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error]         at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$2(ZincComponentCompiler.scala:256)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.util.BufferedLogger.bufferQuietly(BufferedLogger.scala:106)
[error]         at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1(ZincComponentCompiler.scala:256)
[error]         at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1$adapted(ZincComponentCompiler.scala:253)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
[error]         at sbt.internal.inc.ZincComponentCompiler.compileAndInstall(ZincComponentCompiler.scala:253)
[error]         at sbt.internal.inc.ZincComponentCompiler.$anonfun$compiledBridgeJar$1(ZincComponentCompiler.scala:219)
[error]         at sbt.internal.inc.IfMissing$Define.run(IfMissing.scala:19)
[error]         at sbt.internal.inc.ZincComponentManager.createAndCache$1(ZincComponentManager.scala:46)
[error]         at sbt.internal.inc.ZincComponentManager.$anonfun$files$3(ZincComponentManager.scala:57)
[error]         at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:38)
[error]         at sbt.internal.inc.ZincComponentManager.$anonfun$files$2(ZincComponentManager.scala:57)
[error]         at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:87)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:87)
[error]         at sbt.internal.inc.ZincComponentManager.$anonfun$lockSecondaryCache$1(ZincComponentManager.scala:84)
[error]         at scala.Option.map(Option.scala:146)
[error]         at sbt.internal.inc.ZincComponentManager.lockSecondaryCache(ZincComponentManager.scala:82)
[error]         at sbt.internal.inc.ZincComponentManager.fromSecondary$1(ZincComponentManager.scala:55)
[error]         at sbt.internal.inc.ZincComponentManager.$anonfun$files$6(ZincComponentManager.scala:61)
[error]         at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:38)
[error]         at sbt.internal.inc.ZincComponentManager.$anonfun$files$5(ZincComponentManager.scala:61)
[error]         at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:87)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:87)
[error]         at sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:78)
[error]         at sbt.internal.inc.ZincComponentManager.files(ZincComponentManager.scala:61)
[error]         at sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:66)
[error]         at sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:219)
[error]         at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:84)
[error]         at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:91)
[error]         at sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:249)
[error]         at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:267)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:234)
[error]         at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:134)
[error]         at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:121)
[error]         at sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:78)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:88)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1429)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1403)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.base/java.lang.Thread.run(Unknown Source)
[error] (Compile / compileIncremental) java.lang.reflect.InvocationTargetException
[error] Total time: 19 s, completed Jul 31, 2018, 4:07:46 AM

**Comment by ucbjrl** [comment]
Could you provide some more details about your environment:
 - OS
 - sbt version
 - java version

**Comment by eahmedsalman** [comment]
windows 10 
newest version of both sbt and java

**Comment by eahmedsalman** [comment]
i switched to linux and it worked fine but i donot know why its not working on windows

**Comment by jackkoenig** [comment]
By "newest version" of java, do you mean Java 10? Scala and SBT have historically been spotty with Java 10. Can you try Java 8?
