### ISSUE TITLE
sbt run fails with EvalException

### ISSUE THREAD

**Issue by DDRDmakar** [ucb-bar/chisel-tutorial#164]
Hello, I'm a beginner in chisel.  
My system is:  
x86_64 linux Fedora 30  
I installed sbt (0.13.1) and scala (2.10.6)  
my java:
```
[DDRDmakar@localhost chisel-tutorial-3.1.0]$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
I cloned your repo as it shown in readme  
But I get an exception when trying to run "sbt run".
The console log is here:
```
[DDRDmakar@localhost chisel-tutorial-3.1.0]$ sbt run
Getting org.scala-sbt sbt 1.1.1 ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.1/sbt-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#sbt;1.1.1!sbt.jar (71ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-library;2.12.4!scala-library.jar (549ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.1.1/main_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#main_2.12;1.1.1!main_2.12.jar (212ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/logic_2.12/1.1.1/logic_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#logic_2.12;1.1.1!logic_2.12.jar (65ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/actions_2.12/1.1.1/actions_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#actions_2.12;1.1.1!actions_2.12.jar (78ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main-settings_2.12/1.1.1/main-settings_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#main-settings_2.12;1.1.1!main-settings_2.12.jar (117ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/run_2.12/1.1.1/run_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#run_2.12;1.1.1!run_2.12.jar (63ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/command_2.12/1.1.1/command_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#command_2.12;1.1.1!command_2.12.jar (80ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/collections_2.12/1.1.1/collections_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#collections_2.12;1.1.1!collections_2.12.jar (87ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar ...
        [SUCCESSFUL ] org.scala-lang.modules#scala-xml_2.12;1.0.6!scala-xml_2.12.jar(bundle) (108ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.2/launcher-interface-1.0.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.2!launcher-interface.jar (60ms)
downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar ...
        [SUCCESSFUL ] org.apache.logging.log4j#log4j-api;2.8.1!log4j-api.jar (78ms)
downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar ...
        [SUCCESSFUL ] org.apache.logging.log4j#log4j-core;2.8.1!log4j-core.jar (185ms)
downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-slf4j-impl/2.8.1/log4j-slf4j-impl-2.8.1.jar ...
        [SUCCESSFUL ] org.apache.logging.log4j#log4j-slf4j-impl;2.8.1!log4j-slf4j-impl.jar (60ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.1.4/io_2.12-1.1.4.jar ...
        [SUCCESSFUL ] org.scala-sbt#io_2.12;1.1.4!io_2.12.jar (204ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.12/1.1.2/util-logging_2.12-1.1.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-logging_2.12;1.1.2!util-logging_2.12.jar (82ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-core_2.12/1.1.3/librarymanagement-core_2.12-1.1.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#librarymanagement-core_2.12;1.1.3!librarymanagement-core_2.12.jar (126ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-ivy_2.12/1.1.3/librarymanagement-ivy_2.12-1.1.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#librarymanagement-ivy_2.12;1.1.3!librarymanagement-ivy_2.12.jar (114ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.1.1/compiler-interface-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#compiler-interface;1.1.1!compiler-interface.jar (65ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile_2.12/1.1.1/zinc-compile_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-compile_2.12;1.1.1!zinc-compile_2.12.jar (58ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.12/1.1.2/util-relation_2.12-1.1.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-relation_2.12;1.1.2!util-relation_2.12.jar (61ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.12/0.8.2/sjson-new-scalajson_2.12-0.8.2.jar ...
        [SUCCESSFUL ] com.eed3si9n#sjson-new-scalajson_2.12;0.8.2!sjson-new-scalajson_2.12.jar (61ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.12/1.1.2/util-position_2.12-1.1.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-position_2.12;1.1.2!util-position_2.12.jar (67ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.12/0.8.2/sjson-new-core_2.12-0.8.2.jar ...
        [SUCCESSFUL ] com.eed3si9n#sjson-new-core_2.12;0.8.2!sjson-new-core_2.12.jar (133ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/completion_2.12/1.1.1/completion_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#completion_2.12;1.1.1!completion_2.12.jar (81ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/task-system_2.12/1.1.1/task-system_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#task-system_2.12;1.1.1!task-system_2.12.jar (68ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/tasks_2.12/1.1.1/tasks_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#tasks_2.12;1.1.1!tasks_2.12.jar (66ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/testing_2.12/1.1.1/testing_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#testing_2.12;1.1.1!testing_2.12.jar (76ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-tracking_2.12/1.1.2/util-tracking_2.12-1.1.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-tracking_2.12;1.1.2!util-tracking_2.12.jar (63ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.12/1.1.1/zinc-classpath_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-classpath_2.12;1.1.1!zinc-classpath_2.12.jar (70ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.12/1.1.1/zinc-apiinfo_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-apiinfo_2.12;1.1.1!zinc-apiinfo_2.12.jar (83ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-ivy-integration_2.12/1.1.1/zinc-ivy-integration_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-ivy-integration_2.12;1.1.1!zinc-ivy-integration_2.12.jar (71ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.1.1/zinc_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc_2.12;1.1.1!zinc_2.12.jar (63ms)
downloading https://repo1.maven.org/maven2/jline/jline/2.14.4/jline-2.14.4.jar ...
        [SUCCESSFUL ] jline#jline;2.14.4!jline.jar (84ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.12/1.1.2/util-control_2.12-1.1.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-control_2.12;1.1.2!util-control_2.12.jar (59ms)
downloading https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.5.0/jna-4.5.0.jar ...
        [SUCCESSFUL ] net.java.dev.jna#jna;4.5.0!jna.jar (184ms)
downloading https://repo1.maven.org/maven2/net/java/dev/jna/jna-platform/4.5.0/jna-platform-4.5.0.jar ...
        [SUCCESSFUL ] net.java.dev.jna#jna-platform;4.5.0!jna-platform.jar (287ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.1.2/util-interface-1.1.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-interface;1.1.2!util-interface.jar (61ms)
downloading https://repo1.maven.org/maven2/com/lmax/disruptor/3.3.6/disruptor-3.3.6.jar ...
        [SUCCESSFUL ] com.lmax#disruptor;3.3.6!disruptor.jar (67ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-reflect;2.12.4!scala-reflect.jar (518ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.4/scala-compiler-2.12.4.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-compiler;2.12.4!scala-compiler.jar (1011ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.12/1.1.2/util-cache_2.12-1.1.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-cache_2.12;1.1.2!util-cache_2.12.jar (74ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-murmurhash_2.12/0.8.2/sjson-new-murmurhash_2.12-0.8.2.jar ...
        [SUCCESSFUL ] com.eed3si9n#sjson-new-murmurhash_2.12;0.8.2!sjson-new-murmurhash_2.12.jar (57ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-agent/1.1.1/test-agent-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#test-agent;1.1.1!test-agent.jar (62ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.12/1.1.1/zinc-classfile_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-classfile_2.12;1.1.1!zinc-classfile_2.12.jar (64ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.12/0.3.0/gigahorse-okhttp_2.12-0.3.0.jar ...
        [SUCCESSFUL ] com.eed3si9n#gigahorse-okhttp_2.12;0.3.0!gigahorse-okhttp_2.12.jar (64ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.3.0/gigahorse-core_2.12-0.3.0.jar ...
        [SUCCESSFUL ] com.eed3si9n#gigahorse-core_2.12;0.3.0!gigahorse-core_2.12.jar (72ms)
downloading https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.7.0/okhttp-3.7.0.jar ...
        [SUCCESSFUL ] com.squareup.okhttp3#okhttp;3.7.0!okhttp.jar (96ms)
downloading https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2.jar ...
        [SUCCESSFUL ] com.typesafe#ssl-config-core_2.12;0.2.2!ssl-config-core_2.12.jar(bundle) (82ms)
downloading https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.jar ...
        [SUCCESSFUL ] org.reactivestreams#reactive-streams;1.0.0!reactive-streams.jar (59ms)
downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar ...
        [SUCCESSFUL ] org.slf4j#slf4j-api;1.7.25!slf4j-api.jar (62ms)
downloading https://repo1.maven.org/maven2/com/typesafe/config/1.2.0/config-1.2.0.jar ...
        [SUCCESSFUL ] com.typesafe#config;1.2.0!config.jar(bundle) (77ms)
downloading https://repo1.maven.org/maven2/com/squareup/okio/okio/1.12.0/okio-1.12.0.jar ...
        [SUCCESSFUL ] com.squareup.okio#okio;1.12.0!okio.jar (64ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.12/1.1.1/zinc-compile-core_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-compile-core_2.12;1.1.1!zinc-compile-core_2.12.jar (78ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.5/scala-parser-combinators_2.12-1.0.5.jar ...
        [SUCCESSFUL ] org.scala-lang.modules#scala-parser-combinators_2.12;1.0.5!scala-parser-combinators_2.12.jar(bundle) (78ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.12/1.1.1/zinc-core_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-core_2.12;1.1.1!zinc-core_2.12.jar (88ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.12/1.1.1/zinc-persist_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-persist_2.12;1.1.1!zinc-persist_2.12.jar (219ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbinary_2.12/0.4.4/sbinary_2.12-0.4.4.jar ...
        [SUCCESSFUL ] org.scala-sbt#sbinary_2.12;0.4.4!sbinary_2.12.jar (75ms)
downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.3.1/protobuf-java-3.3.1.jar ...
        [SUCCESSFUL ] com.google.protobuf#protobuf-java;3.3.1!protobuf-java.jar(bundle) (181ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/core-macros_2.12/1.1.1/core-macros_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#core-macros_2.12;1.1.1!core-macros_2.12.jar (68ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/protocol_2.12/1.1.1/protocol_2.12-1.1.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#protocol_2.12;1.1.1!protocol_2.12.jar (96ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ipcsocket/ipcsocket/1.0.0/ipcsocket-1.0.0.jar ...
        [SUCCESSFUL ] org.scala-sbt.ipcsocket#ipcsocket;1.0.0!ipcsocket.jar (62ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310/ivy-2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310.jar ...
        [SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310!ivy.jar (159ms)
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        75 artifacts copied, 0 already retrieved (27554kB/42ms)
[info] Loading project definition from /media/STOPKA/EDU/Диплом бакалавра/chisel-tutorial-3.1.0/project
[info] Updating {file:/media/STOPKA/EDU/%D0%94%D0%B8%D0%BF%D0%BB%D0%BE%D0%BC%20%D0%B1%D0%B0%D0%BA%D0%B0%D0%BB%D0%B0%D0%B2%D1%80%D0%B0/chisel-tutorial-3.1.0/project/}chisel-tutorial-3-1-0-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-b18f59ea3bc914a297bb6f1a4f7fb0ace399e310 .[info] Resolving org.scala-lang#scala-reflect;2.10.6 ...
[info] downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1-tests.jar ...
[info]  [SUCCESSFUL ] org.apache.logging.log4j#log4j-core;2.8.1!log4j-core.jar(test-jar) (263ms)
[info] Done updating.
error: bad symbolic reference. A signature in package.class refers to type compileTimeOnly
in package scala.annotation which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling package.class.
/media/STOPKA/EDU/Диплом бакалавра/chisel-tutorial-3.1.0/build.sbt:42: error: Reference to method any2ArrowAssoc in object Predef should not have survived past type checking,
it should have been processed and eliminated during expansion of an enclosing macro.
  "chisel3" -> "3.1.+",
  ^
/media/STOPKA/EDU/Диплом бакалавра/chisel-tutorial-3.1.0/build.sbt:43: error: Reference to method -> in class ArrowAssoc should not have survived past type checking,
it should have been processed and eliminated during expansion of an enclosing macro.
  "chisel-iotesters" -> "1.2.+"
                     ^
/media/STOPKA/EDU/Диплом бакалавра/chisel-tutorial-3.1.0/build.sbt:43: error: Reference to method any2ArrowAssoc in object Predef should not have survived past type checking,
it should have been processed and eliminated during expansion of an enclosing macro.
  "chisel-iotesters" -> "1.2.+"
  ^
sbt.compiler.EvalException: Type error in expression
        at sbt.compiler.Eval.checkError(Eval.scala:343)
        at sbt.compiler.Eval.compileAndLoad(Eval.scala:165)
        at sbt.compiler.Eval.evalCommon(Eval.scala:135)
        at sbt.compiler.Eval.evalDefinitions(Eval.scala:109)
        at sbt.EvaluateConfigurations$.evaluateDefinitions(EvaluateConfigurations.scala:125)
        at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:48)
        at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:502)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:497)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:496)
        at scala.Option.getOrElse(Option.scala:120)
        at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:496)
        at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:495)
        at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:495)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Load$.loadSettings$1(Load.scala:495)
        at sbt.Load$.sbt$Load$$expand$1(Load.scala:508)
        at sbt.Load$.loadSettings(Load.scala:512)
        at sbt.Load$.sbt$Load$$loadSbtFiles$1(Load.scala:466)
        at sbt.Load$.defaultLoad$1(Load.scala:472)
        at sbt.Load$.loadTransitive(Load.scala:475)
        at sbt.Load$.loadProjects$1(Load.scala:421)
        at sbt.Load$.loadUnit(Load.scala:422)
        at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:258)
        at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:258)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:92)
        at sbt.BuildLoader.apply(BuildLoader.scala:143)
        at sbt.Load$.loadAll(Load.scala:314)
        at sbt.Load$.loadURI(Load.scala:266)
        at sbt.Load$.load(Load.scala:262)
        at sbt.Load$.load(Load.scala:253)
        at sbt.Load$.apply(Load.scala:137)
        at sbt.Load$.defaultLoad(Load.scala:40)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:451)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:445)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:445)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$.process(Command.scala:95)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
        at sbt.State$$anon$1.process(State.scala:179)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.MainLoop$.next(MainLoop.scala:100)
        at sbt.MainLoop$.run(MainLoop.scala:93)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
        at sbt.Using.apply(Using.scala:25)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
        at sbt.MainLoop$.runLogged(MainLoop.scala:25)
        at sbt.StandardMain$.runManaged(Main.scala:57)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.explicit(Launch.scala:45)
        at xsbt.boot.Launch$.initialized(Launch.scala:41)
        at xsbt.boot.Launch$.parsed(Launch.scala:34)
        at xsbt.boot.Launch$.configured(Launch.scala:24)
        at xsbt.boot.Launch$.apply(Launch.scala:19)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.run(Boot.scala:26)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[error] Not a valid command: run
[error] run
[error]    ^
```

**Comment by ucbjrl** [comment]
This is quite an old version of chisel-tutorial (excuse us for not tagging a more recent release). Please try cloning the current head of the release branch:
```
git clone https://github.com/ucb-bar/chisel-tutorial.git
cd chisel-tutorial
git checkout release
git pull
```

**Comment by ucbjrl** [comment]
I've just bumped the current release to match the tip of the release branch.

**NOTE**: we expect you to build chisel-tutorial from source, by cloning the GitHub repository and checking out the release branch.

The appropriate versions of `sbt` and `Scala` will be selected by the build.sbt in the release branch commits.

**Comment by DDRDmakar** [comment]
Thanks for the quick support!   
I cloned branch "origin/release" into empty directory and tried "sbt run" again, but get the same error.  
Am I right, that it's enough to have this installed to build chisel tutorial?
- java  (jdk and jre)
- sbt  
- scala  
Or there are another dependences?

**Comment by ucbjrl** [comment]
`java` and `sbt` are the only dependencies. `sbt` should download any required dependencies (including the correct version of `Scala`). The errors look like the `sbt` version is incorrect. Could you please try running the following in the chisel-tutorial folder:
```
sbt about
```
and past the results in this issue.

**Comment by DDRDmakar** [comment]
```
        ...
        ...
        at xsbt.boot.Boot$.run(Boot.scala:26)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[info] This is sbt 1.3.10
[info] No project is currently loaded
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.6
[DDRDmakar@localhost chisel-tutorial]$
```

**Comment by ucbjrl** [comment]
There's something fundamentally wrong with your `sbt`. sbt 1.3.10 requires Scala 2.12. You should be seeing something like:
```
[info] Loading project definition from .../chisel-tutorial/project
[info] Loading settings for project chisel-tutorial from build.sbt ...
[info] Set current project to chisel-tutorial (in build file:.../chisel-tutorial/)
[info] This is sbt 1.3.10
[info] The current project is ProjectRef(uri("file:.../chisel-tutorial/"), "chisel-tutorial") 3.3.0
[info] The current project is built against Scala 2.12.10
[info] Available Plugins
[info]  - com.typesafe.sbt.SbtPgp
[info]  - sbt.ScriptedPlugin
[info]  - sbt.plugins.CorePlugin
[info]  - sbt.plugins.Giter8TemplatePlugin
[info]  - sbt.plugins.IvyPlugin
[info]  - sbt.plugins.JUnitXmlReportPlugin
[info]  - sbt.plugins.JvmPlugin
[info]  - sbt.plugins.SbtPlugin
[info]  - sbt.plugins.SemanticdbPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.12.10

```

**Comment by ucbjrl** [comment]
Could you try installing a version of `sbt` greater than 0.13?

**Comment by DDRDmakar** [comment]
Yes, it's something wrong with sbt from fedora repositories.  
I tried another machine with antiX linux and everything works perfect there!  
"sbt about" on antiX gives exactly the same results as in your comment.  
So, it's better to use official repository from SBT website:  
[https://www.scala-sbt.org/download.html]()  
YaY

**Comment by ucbjrl** [comment]
Good to hear.

`sbt` 0.13.1 dates from Dec 10, 2013. This is incredible. Fedora 30, whose release was announced in [April, 2019](https://fedoramagazine.org/announcing-fedora-30/), includes [sbt 0.13.1](https://fedora.pkgs.org/30/fedora-x86_64/sbt-0.13.1-9.fc28.1.noarch.rpm.html) as their default (and only) version of `sbt`.
