### ISSUE TITLE
DynamicMemorySearch Error

### ISSUE THREAD

**Issue by peterhchen** [ucb-bar/chisel-tutorial#179]
./run-problem.sh DynamicMemorySearch
[info] Loading project definition from /home/peter/AIU/AIU_CS800_Chisel/600_UCB_Chisel/010_Problem/chisel-tutorial-release/project
[info] Loading settings for project chisel-tutorial-release from build.sbt ...
[info] Set current project to chisel-tutorial (in build file:/home/peter/AIU/AIU_CS800_Chisel/600_UCB_Chisel/010_Problem/chisel-tutorial-release/)
[info] Compiling 56 Scala sources to /home/peter/AIU/AIU_CS800_Chisel/600_UCB_Chisel/010_Problem/chisel-tutorial-release/target/scala-2.12/classes ...
[info] Compiling 63 Scala sources to /home/peter/AIU/AIU_CS800_Chisel/600_UCB_Chisel/010_Problem/chisel-tutorial-release/target/scala-2.12/test-classes ...
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] running problems.Launcher DynamicMemorySearch
Starting tutorial DynamicMemorySearch
[info] [0.001] Elaborating design...
[info] [0.833] Done elaborating.
Computed transform order in: 285.1 ms
Total FIRRTL Compile Time: 559.1 ms
file loaded in 0.074084106 seconds, 21 symbols, 15 statements
[info] [0.001] SEED 1734596278520
java.lang.AssertionError: assertion failed: LOOKING FOR 8 FOUND 7
	at scala.Predef$.assert(Predef.scala:223)
	at problems.DynamicMemorySearchTests.$anonfun$new$2(DynamicMemorySearchTests.scala:39)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at problems.DynamicMemorySearchTests.<init>(DynamicMemorySearchTests.scala:17)
	at problems.Launcher$.$anonfun$tests$30(Launcher.scala:57)
	at chisel3.iotesters.Driver$.$anonfun$execute$4(Driver.scala:68)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at chisel3.iotesters.Driver$.$anonfun$execute$2(Driver.scala:67)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:168)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at logger.Logger$.makeScope(Logger.scala:166)
	at logger.Logger$.makeScope(Logger.scala:127)
	at chisel3.iotesters.Driver$.$anonfun$execute$1(Driver.scala:38)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at chisel3.iotesters.Driver$.execute(Driver.scala:38)
	at problems.Launcher$.$anonfun$tests$28(Launcher.scala:57)
	at problems.Launcher$.$anonfun$tests$28$adapted(Launcher.scala:55)
	at utils.TutorialRunner$.$anonfun$apply$3(TutorialRunner.scala:56)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at utils.TutorialRunner$.apply(TutorialRunner.scala:47)
	at problems.Launcher$.main(Launcher.scala:104)
	at problems.Launcher.main(Launcher.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:115)
	at sbt.Run.execute$1(Run.scala:79)
	at sbt.Run.$anonfun$runWithLoader$3(Run.scala:84)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.Run.directExecute$1(Run.scala:84)
	at sbt.Run.runWithLoader(Run.scala:93)
	at sbt.Defaults$.$anonfun$bgRunMainTask$7(Defaults.scala:1458)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:360)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
================================================================================
Errors: 1: in the following tutorials
Tutorial DynamicMemorySearch: throwable assertion failed: LOOKING FOR 8 FOUND 7
================================================================================
2024-12-19 00:18:00,981 shutdown-hooks-run-all ERROR No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2

**Comment by peterhchen** [comment]
// Problem in src/main/scala/problems/DynamicMemorySearch.scala is fixed 
// at src/main/scala/solutions/DynamicMemorySearch.scala
// See LICENSE.txt for license details.
package solutions

import chisel3._
import chisel3.util.log2Ceil

// Problem:
//
// This module should be able to write 'data' to
// internal memory at 'wrAddr' if 'isWr' is asserted.
//
// This module should perform sequential search of 'data'
// in internal memory if 'en' was asserted at least 1 clock cycle
//
// While searching 'done' should remain 0,
// 'done' should be asserted when search is complete
//
// If 'data' has been found 'target' should be updated to the
// address of the first occurrence
//
class DynamicMemorySearch(val n: Int, val w: Int) extends Module {
  val io = IO(new Bundle {
    val isWr   = Input(Bool())
    val wrAddr = Input(UInt(log2Ceil(n).W))
    val data   = Input(UInt(w.W))
    val en     = Input(Bool())
    val target = Output(UInt(log2Ceil(n).W))
    val done   = Output(Bool())
  })
  val index  = RegInit(0.U(log2Ceil(n).W))

  val list   = Mem(n, UInt(w.W))
  val memVal = list(index)

  val done   = !io.en && ((memVal === io.data) || (index === (n-1).asUInt))

  when (io.isWr) {
    list(io.wrAddr) := io.data
  } .elsewhen (io.en) {
    index := 0.U
  } .elsewhen (done === false.B) {
    index := index + 1.U
  }
  io.done   := done
  io.target := index
}
