### ISSUE TITLE
Error when running the examples

### ISSUE THREAD

**Issue by sorooshstrife** [ucb-bar/chisel-tutorial#88]
Hi. `sbt run` and `test:run-main problems.Launcher Mux2`  work fine. But all other examples fail.

`test:run-main problems.Launcher Mux4`

Produces:
```
[info] Running problems.Launcher Mux4
Starting tutorial Mux4
[info] [0.002] Elaborating design...
[info] [0.089] Done elaborating.
Total FIRRTL Compile Time: 195.8 ms
Total FIRRTL Compile Time: 38.1 ms
End of dependency graph
Circuit state created
[info] [0.001] SEED 1498765114985
[info] [0.009] EXPECT AT 9   io_out got 0 expected 1 FAIL
[info] [0.009] EXPECT AT 10   io_out got 0 expected 1 FAIL
[info] [0.010] EXPECT AT 11   io_out got 0 expected 1 FAIL
[info] [0.011] EXPECT AT 12   io_out got 0 expected 1 FAIL
[info] [0.012] EXPECT AT 13   io_out got 0 expected 1 FAIL
[info] [0.013] EXPECT AT 14   io_out got 0 expected 1 FAIL
[info] [0.014] EXPECT AT 15   io_out got 0 expected 1 FAIL
[info] [0.014] EXPECT AT 16   io_out got 0 expected 1 FAIL
[info] [0.016] EXPECT AT 19   io_out got 0 expected 1 FAIL
[info] [0.017] EXPECT AT 20   io_out got 0 expected 1 FAIL
[info] [0.019] EXPECT AT 23   io_out got 0 expected 1 FAIL
[info] [0.019] EXPECT AT 24   io_out got 0 expected 1 FAIL
[info] [0.021] EXPECT AT 27   io_out got 0 expected 1 FAIL
[info] [0.022] EXPECT AT 28   io_out got 0 expected 1 FAIL
[info] [0.024] EXPECT AT 31   io_out got 0 expected 1 FAIL
[info] [0.024] EXPECT AT 32   io_out got 0 expected 1 FAIL
[info] [0.027] EXPECT AT 37   io_out got 0 expected 1 FAIL
[info] [0.028] EXPECT AT 38   io_out got 0 expected 1 FAIL
[info] [0.029] EXPECT AT 39   io_out got 0 expected 1 FAIL
[info] [0.029] EXPECT AT 40   io_out got 0 expected 1 FAIL
[info] [0.032] EXPECT AT 45   io_out got 0 expected 1 FAIL
[info] [0.033] EXPECT AT 46   io_out got 0 expected 1 FAIL
[info] [0.033] EXPECT AT 47   io_out got 0 expected 1 FAIL
[info] [0.034] EXPECT AT 48   io_out got 0 expected 1 FAIL
[info] [0.035] EXPECT AT 50   io_out got 0 expected 1 FAIL
[info] [0.036] EXPECT AT 52   io_out got 0 expected 1 FAIL
[info] [0.037] EXPECT AT 54   io_out got 0 expected 1 FAIL
[info] [0.038] EXPECT AT 56   io_out got 0 expected 1 FAIL
[info] [0.039] EXPECT AT 58   io_out got 0 expected 1 FAIL
[info] [0.041] EXPECT AT 60   io_out got 0 expected 1 FAIL
[info] [0.042] EXPECT AT 62   io_out got 0 expected 1 FAIL
[info] [0.043] EXPECT AT 64   io_out got 0 expected 1 FAIL
test Mux4 Success: 32 tests passed in 69 cycles taking 0.049389 seconds
[info] [0.043] RAN 64 CYCLES FAILED FIRST AT CYCLE 9
================================================================================
Errors: 1: in the following tutorials
Tutorial Mux4: test error occurred
================================================================================

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread `"run-main-0"
`java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        [trace] Stack trace suppressed: run last test:runMain for the full output.
[error] (test:runMain) Nonzero exit code: 1
[error] Total time: 1 s, completed 29-Jun-2017 2:38:35 PM
```

And the output for `last test:runMain`

```
[info] Running problems.Launcher Mux4
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug]         /home/soroosh/soroosh/chisel-tutorial/target/scala-2.11/test-classes
[debug]         /home/soroosh/soroosh/chisel-tutorial/target/scala-2.11/classes
[debug]         /home/soroosh/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar
[debug]         /home/soroosh/.ivy2/cache/edu.berkeley.cs/chisel3_2.11/jars/chisel3_2.11-3.0-SNAPSHOT.jar
[debug]         /home/soroosh/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.7.jar
[debug]         /home/soroosh/.ivy2/cache/edu.berkeley.cs/firrtl_2.11/jars/firrtl_2.11-1.0-SNAPSHOT.jar
[debug]         /home/soroosh/.ivy2/cache/com.typesafe.scala-logging/scala-logging_2.11/bundles/scala-logging_2.11-3.5.0.jar
[debug]         /home/soroosh/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.21.jar
[debug]         /home/soroosh/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar
[debug]         /home/soroosh/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.7.jar
[debug]         /home/soroosh/.ivy2/cache/com.github.scopt/scopt_2.11/jars/scopt_2.11-3.5.0.jar
[debug]         /home/soroosh/.ivy2/cache/net.jcazevedo/moultingyaml_2.11/jars/moultingyaml_2.11-0.4.0.jar
[debug]         /home/soroosh/.ivy2/cache/com.github.nscala-time/nscala-time_2.11/jars/nscala-time_2.11-2.14.0.jar
[debug]         /home/soroosh/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.4.jar
[debug]         /home/soroosh/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.2.jar
[debug]         /home/soroosh/.ivy2/cache/org.yaml/snakeyaml/bundles/snakeyaml-1.17.jar
[debug]         /home/soroosh/.ivy2/cache/org.antlr/antlr4/jars/antlr4-4.5.3.jar
[debug]         /home/soroosh/.ivy2/cache/org.antlr/antlr4-runtime/jars/antlr4-runtime-4.5.3.jar
[debug]         /home/soroosh/.ivy2/cache/edu.berkeley.cs/chisel-iotesters_2.11/jars/chisel-iotesters_2.11-1.1-SNAPSHOT.jar
[debug]         /home/soroosh/.ivy2/cache/edu.berkeley.cs/firrtl-interpreter_2.11/jars/firrtl-interpreter_2.11-1.0-SNAPSHOT.jar
[debug]         /home/soroosh/.ivy2/cache/org.scalatest/scalatest_2.11/bundles/scalatest_2.11-3.0.1.jar
[debug]         /home/soroosh/.ivy2/cache/org.scalactic/scalactic_2.11/bundles/scalactic_2.11-3.0.1.jar
[debug]         /home/soroosh/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.5.jar
[debug]         /home/soroosh/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar
[debug]         /home/soroosh/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.13.4.jar
[debug]         /home/soroosh/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar
[debug]         /home/soroosh/.ivy2/cache/org.scala-lang.modules/scala-jline/bundles/scala-jline-2.12.1.jar
[debug]         /home/soroosh/.ivy2/cache/org.fusesource.jansi/jansi/jars/jansi-1.11.jar
[debug] Waiting for thread run-main-0 to terminate.
[debug] Interrupting thread run-main-0
[debug]         Interrupted run-main-0
[debug]         Thread run-main-0 exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Sandboxed run complete..
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2081)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2081)
        at scala.Option.foreach(Option.scala:236)
        at sbt.BuildCommon$class.toError(Defaults.scala:2081)
        at sbt.Defaults$.toError(Defaults.scala:39)
        at sbt.Defaults$$anonfun$runMainTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:740)
        at sbt.Defaults$$anonfun$runMainTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:738)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] (test:runMain) Nonzero exit code: 1

```

**Comment by ucbjrl** [comment]
The error you are reporting is for `problems/Mux4.scala`. Problems are supposed to fail. The purpose of the problems directory is to provide Chisel code examples that need changing in order to function correctly. You should edit your local copy of the code so that it passes the tests.
